name: we_are_friends_app
description:  Приложение для совместного сбора денег


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+4

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls

  intl: ^0.17.0
  flutter_svg: ^1.0.3
  simple_shadow: ^0.3.0
  flutter_slidable: ^1.2.0
  slidable_button: ^1.3.1
  flutter_fadein: ^2.0.0
  jiffy: ^5.0.0
  hive: ^2.2.3
  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0+2
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.8.2
  image_picker_for_web: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.11.0

flutter_icons:
 # image_path_android: "assets/app_icon.png"
 # image_path_ios: "assets/app_icon.png"
 # android: false # can specify file name here e.g. "ic_launcher"
 # ios: true
 # remove_alpha_ios: true
  android: false
  ios: true
  remove_alpha_ios: true
  image_path_android: C:\Users\Acer\Private\Work\NSG_software\NSG_we_are_friends_app\Identity\Launch_icon\Launch_icon_android_png\NSG_we_are_friends_app_512х512_icon.png
  image_path_ios: C:\Users\Acer\Private\Work\NSG_software\NSG_we_are_friends_app\Identity\Launch_icon\Launch_icon_ios_png\NSG_we_are_friends_app_1024х1024_icon.png
  # min_sdk_android: 21 # android min sdk min:16, default 21
  #web:
    #generate: true
    #image_path: "path/to/image.png"
    #background_color: "#ffffff"
    #theme_color: "#ffffff"
  #windows:
    #generate: true
    #image_path: "path/to/image.png"
    #icon_size: 48 # min:48, max:256, default: 48
  #macos:
    #generate: true
    #image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
